name: ci
on:
  pull_request:
  workflow_dispatch:  # manual run button

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true  # auto-cancel old runs when you push new commits

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-west-1
      SUBSCRIPTIONS_TABLE: Subscriptions-dev

      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET || 'dummy' }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      STRIPE_PRICE_ID: ${{ secrets.STRIPE_PRICE_ID }}
      STRIPE_PRODUCT_ID: ${{ secrets.STRIPE_PRODUCT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install python-dotenv stripe moto boto3 aws-cdk-lib
      - name: Run tests
        run: pytest -ra

